// Original, locally generated artwork. Stable IDs keep browsing separate from project data.
export const GENRES = ["Fantasy", "Cozy", "School life", "Romcom"];

const human = (id, name, genre, description, look) => ({
  id,
  name,
  genre,
  description,
  kind: "character",
  species: "Human",
  ...look,
});

export const HUMAN_CHARACTERS = [
  human(
    "village-adventurer",
    "Village adventurer",
    "Fantasy",
    "A green tunic, leather boots, and a red scarf for the road ahead.",
    {
      skin: "tan",
      hair: "short",
      hairColor: "brown",
      outfit: "tunic",
      color: "green",
      accent: "red",
      accessory: "scarf",
    },
  ),
  human(
    "royal-knight",
    "Royal knight",
    "Fantasy",
    "Silver plate armor and a blue cape, ready for a quest.",
    {
      skin: "deep",
      hair: "short",
      hairColor: "black",
      outfit: "armor",
      color: "steel",
      accent: "blue",
      accessory: "cape",
    },
  ),
  human(
    "starlight-mage",
    "Starlight mage",
    "Fantasy",
    "A violet robe and pointed hat for a human spellcaster.",
    {
      skin: "light",
      hair: "long",
      hairColor: "silver",
      outfit: "robe",
      color: "purple",
      accent: "gold",
      accessory: "hat",
    },
  ),
  human(
    "woodland-ranger",
    "Woodland ranger",
    "Fantasy",
    "An earth-toned ranger with a ponytail and forest cloak.",
    {
      skin: "brown",
      hair: "ponytail",
      hairColor: "black",
      outfit: "vest",
      color: "brown",
      accent: "green",
      accessory: "cape",
    },
  ),
  human(
    "palace-healer",
    "Palace healer",
    "Fantasy",
    "Ivory robes, rose accents, and a braided crown of hair.",
    {
      skin: "tan",
      hair: "bob",
      hairColor: "brown",
      outfit: "robe",
      color: "cream",
      accent: "rose",
      accessory: "headband",
    },
  ),
  human(
    "crown-princess",
    "Crown princess",
    "Fantasy",
    "A golden crown above a flowing pink court dress.",
    {
      skin: "brown",
      hair: "long",
      hairColor: "black",
      outfit: "dress",
      color: "rose",
      accent: "gold",
      accessory: "crown",
    },
  ),
  human(
    "cafe-barista",
    "Café barista",
    "Cozy",
    "A coffee-colored apron over a cream shirt.",
    {
      skin: "deep",
      hair: "curly",
      hairColor: "black",
      outfit: "apron",
      color: "cream",
      accent: "brown",
      accessory: "none",
    },
  ),
  human(
    "village-baker",
    "Village baker",
    "Cozy",
    "A striped apron and a baker’s cap for early mornings.",
    {
      skin: "light",
      hair: "bob",
      hairColor: "copper",
      outfit: "apron",
      color: "rose",
      accent: "cream",
      accessory: "cap",
    },
  ),
  human(
    "flower-shopkeeper",
    "Flower shopkeeper",
    "Cozy",
    "A green apron and a flower tucked into long hair.",
    {
      skin: "tan",
      hair: "long",
      hairColor: "brown",
      outfit: "apron",
      color: "cream",
      accent: "green",
      accessory: "flower",
    },
  ),
  human(
    "bookshop-owner",
    "Bookshop owner",
    "Cozy",
    "Round glasses and a plum cardigan for a quiet afternoon.",
    {
      skin: "brown",
      hair: "short",
      hairColor: "silver",
      outfit: "cardigan",
      color: "purple",
      accent: "cream",
      accessory: "glasses",
    },
  ),
  human(
    "weekend-gardener",
    "Weekend gardener",
    "Cozy",
    "Work overalls, a straw hat, and sturdy boots.",
    {
      skin: "deep",
      hair: "curly",
      hairColor: "brown",
      outfit: "overalls",
      color: "green",
      accent: "gold",
      accessory: "sunhat",
    },
  ),
  human(
    "cozy-artist",
    "Cozy artist",
    "Cozy",
    "A blue smock and red beret for a day in the studio.",
    {
      skin: "light",
      hair: "ponytail",
      hairColor: "black",
      outfit: "apron",
      color: "blue",
      accent: "cream",
      accessory: "beret",
    },
  ),
  human(
    "student-council",
    "Student council lead",
    "School life",
    "A navy blazer, red tie, and neatly parted hair.",
    {
      skin: "tan",
      hair: "short",
      hairColor: "black",
      outfit: "blazer",
      color: "navy",
      accent: "red",
      accessory: "none",
    },
  ),
  human(
    "literature-club",
    "Literature club reader",
    "School life",
    "A cream cardigan, round glasses, and a pleated skirt.",
    {
      skin: "light",
      hair: "bob",
      hairColor: "brown",
      outfit: "skirt",
      color: "cream",
      accent: "navy",
      accessory: "glasses",
    },
  ),
  human(
    "track-team",
    "Track team captain",
    "School life",
    "A bright tracksuit with a matching sports headband.",
    {
      skin: "deep",
      hair: "curly",
      hairColor: "black",
      outfit: "tracksuit",
      color: "red",
      accent: "cream",
      accessory: "headband",
    },
  ),
  human(
    "music-club",
    "Music club guitarist",
    "School life",
    "A violet hoodie and headphones for after-school practice.",
    {
      skin: "brown",
      hair: "short",
      hairColor: "black",
      outfit: "hoodie",
      color: "purple",
      accent: "gold",
      accessory: "headphones",
    },
  ),
  human(
    "art-club",
    "Art club dreamer",
    "School life",
    "A blue school cardigan and a ribbon in a high ponytail.",
    {
      skin: "tan",
      hair: "ponytail",
      hairColor: "copper",
      outfit: "skirt",
      color: "blue",
      accent: "navy",
      accessory: "bow",
    },
  ),
  human(
    "transfer-student",
    "Transfer student",
    "School life",
    "A forest-green blazer with a golden tie and a bob haircut.",
    {
      skin: "brown",
      hair: "bob",
      hairColor: "black",
      outfit: "blazer",
      color: "green",
      accent: "gold",
      accessory: "none",
    },
  ),
  human(
    "spring-date",
    "Spring date",
    "Romcom",
    "A rose dress and a flower pin for a cherry-blossom walk.",
    {
      skin: "light",
      hair: "long",
      hairColor: "brown",
      outfit: "dress",
      color: "rose",
      accent: "cream",
      accessory: "flower",
    },
  ),
  human(
    "city-romantic",
    "City romantic",
    "Romcom",
    "A blue jacket and cream shirt for a first coffee date.",
    {
      skin: "deep",
      hair: "curly",
      hairColor: "black",
      outfit: "cardigan",
      color: "blue",
      accent: "cream",
      accessory: "none",
    },
  ),
  human(
    "rainy-day-lead",
    "Rainy-day lead",
    "Romcom",
    "A warm trench coat and a red scarf for missed trains.",
    {
      skin: "tan",
      hair: "short",
      hairColor: "brown",
      outfit: "coat",
      color: "gold",
      accent: "red",
      accessory: "scarf",
    },
  ),
  human(
    "festival-crush",
    "Festival crush",
    "Romcom",
    "A violet yukata, pink sash, and a ribbon in long hair.",
    {
      skin: "brown",
      hair: "long",
      hairColor: "black",
      outfit: "yukata",
      color: "purple",
      accent: "rose",
      accessory: "bow",
    },
  ),
  human(
    "office-sweetheart",
    "Office sweetheart",
    "Romcom",
    "A fitted navy suit, rose tie, and glasses.",
    {
      skin: "light",
      hair: "bob",
      hairColor: "black",
      outfit: "suit",
      color: "navy",
      accent: "rose",
      accessory: "glasses",
    },
  ),
  human(
    "weekend-neighbor",
    "Weekend neighbor",
    "Romcom",
    "A relaxed mint hoodie and sneakers for a chance encounter.",
    {
      skin: "deep",
      hair: "short",
      hairColor: "brown",
      outfit: "hoodie",
      color: "mint",
      accent: "cream",
      accessory: "none",
    },
  ),
];

export const CHARACTER_BASES = [
  "Humanoid male",
  "Humanoid female",
  "Knight",
  "Goblin",
  "Quadruped",
].map((name) => ({
  id: `base-${name.toLowerCase().replaceAll(" ", "-")}`,
  name,
  kind: "character",
  genre: "Basics",
  species: name === "Goblin" || name === "Quadruped" ? "Creature" : "Human",
  description:
    "An original studio base with editable parts and a complete pose hierarchy.",
}));

const scene = (id, name, genre, description, theme, setting) => ({
  id,
  name,
  genre,
  description,
  theme,
  setting,
  kind: "background",
});
export const BACKGROUNDS = [
  scene(
    "moonlit-castle",
    "Moonlit castle",
    "Fantasy",
    "A silver moon, distant mountains, and a castle above the valley.",
    "Castle stone",
    "castle",
  ),
  scene(
    "enchanted-forest",
    "Enchanted forest",
    "Fantasy",
    "Ancient trees, glowing mushrooms, and fireflies beside a forest path.",
    "Enchanted forest",
    "forest",
  ),
  scene(
    "floating-isles",
    "Floating isles",
    "Fantasy",
    "Grassy islands and a waterfall suspended in a cloud-filled sky.",
    "Grassland",
    "islands",
  ),
  scene(
    "lantern-village",
    "Lantern village",
    "Fantasy",
    "Warm windows and hanging lanterns along a medieval village lane.",
    "Cozy village",
    "village",
  ),
  scene(
    "cottage-garden",
    "Cottage garden",
    "Cozy",
    "A flower-lined path, a little cottage, and a white garden fence.",
    "Cozy village",
    "garden",
  ),
  scene(
    "bookshop-corner",
    "Bookshop corner",
    "Cozy",
    "Colorful bookshelves, a reading chair, and a sunlit shop window.",
    "Café interior",
    "bookshop",
  ),
  scene(
    "bakery-morning",
    "Bakery morning",
    "Cozy",
    "A striped awning, warm bread, and a welcoming bakery counter.",
    "Café interior",
    "bakery",
  ),
  scene(
    "seaside-town",
    "Seaside town",
    "Cozy",
    "Pastel houses overlook a bright sea and a small sailboat.",
    "Coastal path",
    "seaside",
  ),
  scene(
    "sunlit-classroom",
    "Sunlit classroom",
    "School life",
    "Rows of desks, a chalkboard, and tall windows in afternoon light.",
    "School floor",
    "classroom",
  ),
  scene(
    "school-rooftop",
    "School rooftop",
    "School life",
    "A quiet fenced rooftop above a blue city skyline.",
    "School floor",
    "rooftop",
  ),
  scene(
    "library-afternoon",
    "Library afternoon",
    "School life",
    "Tall bookshelves surround a shared study table by the window.",
    "School floor",
    "library",
  ),
  scene(
    "station-platform",
    "Station platform",
    "School life",
    "A commuter train, station clock, and a platform for a chance meeting.",
    "School floor",
    "station",
  ),
  scene(
    "sakura-promenade",
    "Sakura promenade",
    "Romcom",
    "Pink cherry blossoms drift over a riverside path and a park bench.",
    "Sakura garden",
    "sakura",
  ),
  scene(
    "corner-cafe",
    "Corner café",
    "Romcom",
    "A pink café awning and a table for two on a neighborhood street.",
    "Café interior",
    "cafe",
  ),
  scene(
    "festival-evening",
    "Festival evening",
    "Romcom",
    "Lantern strings, festival stalls, and fireworks in the evening sky.",
    "Festival paving",
    "festival",
  ),
  scene(
    "sunset-boardwalk",
    "Sunset boardwalk",
    "Romcom",
    "A peach sunset over the sea, with a bench on the wooden pier.",
    "Coastal path",
    "boardwalk",
  ),
];

const prop = (id, name, genre, description) => ({
  id,
  name,
  genre,
  description,
  kind: "prop",
});
export const PROPS = [
  prop(
    "sprout",
    "Sprout",
    "Basics",
    "The studio’s original little forest spirit.",
  ),
  prop(
    "crystal",
    "Crystal",
    "Fantasy",
    "A bright blue crystal for magical scenes.",
  ),
  prop("heart", "Heart", "Romcom", "A tiny pink heart for a big moment."),
  prop("potion", "Potion", "Fantasy", "A corked bottle of violet magic."),
  prop(
    "spellbook",
    "Spellbook",
    "Fantasy",
    "A gold-bound tome with a star on its cover.",
  ),
  prop(
    "treasure-chest",
    "Treasure chest",
    "Fantasy",
    "A wooden chest with gold fittings.",
  ),
  prop("lantern", "Lantern", "Fantasy", "A warm lantern for village evenings."),
  prop(
    "coffee-cup",
    "Coffee cup",
    "Cozy",
    "A steaming cup with a little saucer.",
  ),
  prop("cat", "Cat", "Cozy", "A ginger cat waiting beside the window."),
  prop(
    "bento-box",
    "Bento box",
    "School life",
    "A packed lunch with rice and vegetables.",
  ),
  prop(
    "school-bag",
    "School bag",
    "School life",
    "A blue satchel with a brass buckle.",
  ),
  prop("bouquet", "Bouquet", "Romcom", "Pink and red flowers in a paper wrap."),
  prop(
    "love-letter",
    "Love letter",
    "Romcom",
    "A cream envelope sealed with a heart.",
  ),
  prop(
    "umbrella",
    "Umbrella",
    "Romcom",
    "A pink umbrella for a rainy encounter.",
  ),
  prop(
    "gift-box",
    "Gift box",
    "Romcom",
    "A small present tied with a gold ribbon.",
  ),
];

export const LIBRARY_ASSETS = [
  ...HUMAN_CHARACTERS,
  ...BACKGROUNDS,
  ...PROPS,
  ...CHARACTER_BASES,
];
export const CHARACTER_GROUPS = [...GENRES, "Basics"].map((genre) => ({
  name: genre,
  characters: [...HUMAN_CHARACTERS, ...CHARACTER_BASES].filter(
    (entry) => entry.genre === genre,
  ),
}));

export function filterAssets({ kind = "all", genre = "all", query = "" } = {}) {
  const normalize = (text) =>
    text
      .normalize("NFD")
      .replace(/\p{Diacritic}/gu, "")
      .toLocaleLowerCase();
  const words = normalize(query.trim()).split(/\s+/).filter(Boolean);
  return LIBRARY_ASSETS.filter((asset) => {
    const text = normalize(
      `${asset.name} ${asset.genre} ${asset.description} ${asset.species || ""} ${asset.kind}`,
    );
    return (
      (kind === "all" || asset.kind === kind) &&
      (genre === "all" || asset.genre === genre) &&
      words.every((word) => text.includes(word))
    );
  });
}
